// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyFUXtL6Z236QvI82LTXiSSKIue2QX6Fk',
    appId: '1:210205754206:web:516aea44757bf4c0d3c5cf',
    messagingSenderId: '210205754206',
    projectId: 'komigo-62aea',
    authDomain: 'komigo-62aea.firebaseapp.com',
    storageBucket: 'komigo-62aea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZQwRiawRHTB-QF8tbvrJ0qmx04gqvlvs',
    appId: '1:210205754206:android:7a7c1b715995945ad3c5cf',
    messagingSenderId: '210205754206',
    projectId: 'komigo-62aea',
    storageBucket: 'komigo-62aea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwzbyNF6brAqYsxTWb3qs13yNWXBBjGfo',
    appId: '1:210205754206:ios:28769eaff01530b3d3c5cf',
    messagingSenderId: '210205754206',
    projectId: 'komigo-62aea',
    storageBucket: 'komigo-62aea.appspot.com',
    iosBundleId: 'com.example.restoAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwzbyNF6brAqYsxTWb3qs13yNWXBBjGfo',
    appId: '1:210205754206:ios:7968aa7ebafb25c9d3c5cf',
    messagingSenderId: '210205754206',
    projectId: 'komigo-62aea',
    storageBucket: 'komigo-62aea.appspot.com',
    iosBundleId: 'com.example.restoAdmin.RunnerTests',
  );
}
